# Generated by Django 2.2 on 2022-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profilpic',
            fields=[
                ('pro_count', models.AutoField(primary_key=True, serialize=False)),
                ('img_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('testimonialId', models.AutoField(primary_key=True, serialize=False)),
                ('img_string', models.TextField()),
                ('Full_Name', models.CharField(max_length=200)),
                ('Job_Title', models.CharField(max_length=200)),
                ('Comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('workId', models.AutoField(primary_key=True, serialize=False)),
                ('img_string', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('tag', models.CharField(max_length=200)),
                ('poper', models.CharField(max_length=200)),
                ('project_link', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
